spring.application.name=LibriVeritasApp
environment.name=PROD

# Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://${pgServer}:${pgServerPort}/LibriVeritasDB
spring.datasource.username=${pgUserName}
spring.datasource.password=${pgPassword}

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações opcionais
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.format-sql=false
spring.jpa.hibernate.ddl-auto=update

# Pool de conexões (opcional)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10




